### ISSUE TITLE
Cannot read property 'channeling' of undefined

### ISSUE THREAD

**Issue by stlemme** [xml3d/shade.js#1]
This error appears in various cases.

Message:
Shader: Shade.js Compile Error:
Cannot read property 'channeling' of undefined

Minimal example:
https://github.com/stlemme/xml3d-experimental/tree/master/channeling-bug

**Comment by jasu0x58** [comment]
Fixed. 
See xml3d/xml3d.js@e189bdbf519211e7bf80a047d6887e64164c50ba
